### ISSUE TITLE
Server example doesn't work

### ISSUE THREAD

**Issue by shmish111** [bitnomial/servant-jsonrpc#1]
I can't get the server example to work, can you provide a working example project?

**Comment by GambolingPangolin** [comment]
Oops, just saw this issue.  The example is just a sketch to suggest how it works.  I'll add an example project soon.

**Comment by GambolingPangolin** [comment]
I tried to get an example project running, and found that the routing is completely broken for the server (the client is okay).  In fact, the server module is a bit misguided the way it is currently set up.  Routing has to happen after parsing the request body, but I don't see a way in servant-server to parse the body into an intermediate form, look at the method, then dispatch to a handler.  I think we should avoid parsing the request body over and over again looking for a matching method.

I think that I can implement the following sort of thing, which should be reasonably efficient and is not too far from pure servant.

There would be type `JsonRpcServer` that you can use to terminate a servant api endpoint e.g. 
```haskell
type Rpc = "rpc-server" :> JsonRpcServer
type Rest = "rest-endpoint" :> Get '[JSON] (Maybe Int)
```

There would also be a typeclass function `serveJsonRpc` which you would use in a way similar to Servant's `serve`.

```haskell
type Endpoint1 = JsonRpc "endpoint1" Int String Int
type Endpoint2 = JsonRpc "endpoint2" String String Int

type RpcAPI = Endpoint1 :<|> Endpoint2

endpoint1 :: Int -> Handler (Either (JsonRpcErr String) Int)
endpoint1 = _

endpoint2 :: String -> Handler (Either (JsonRpcErr String) Int)
endpoint2 = _

-- combine implementations
rpcServer = endpoint1 :<|> endpoint2

restEndpointImpl :: Handler (Maybe Int)
restEndpointImpl = _

server = serveJsonRpc (Proxy @RpcAPI) rpcServer :<|> restEndpointImpl

-- finally get the Wai Application 
main = run 8080 $ serve server
```

@shmish111 does that look reasonable to you?

**Comment by shmish111** [comment]
Is it possible to connect a servant api with an rpc api though? Not the end of the world if not, but some people have a lot of other combinators such as SSL termination, authentication etc, I presume these wouldn't work? I ended up just using your types with normal a servant API and doing the routing manually afterwards, as you say, I had parsed the body with the pure servant endpoint however this is not good since the routing is a very important part that servant stuff can help with. So err... I'm not sure

**Comment by GambolingPangolin** [comment]
Yes, I think we can have a mixed API where some routes go to JSON RPC servers, but we need some glue code.  Servant can handle routing by path, populating captures, providing authentication context, etc. in combination with a JSON RPC endpoint.  However, the processing that servant automates does have a limit.  So with only servant we can get to the point where we have to supply `servant-server` with a value like

```haskell
_ :: Request Value -> m (JsonRpcResponse Value Value)
```

Then the library can export a type class for composing values like this from implementations for the individual RPC methods.  So from an end user point of view it would be quite similar to using servant server, except you have to combine your JSON RPC endpoint handlers with a special function, then combine the resulting handler with the rest of the servant API in the usual manner using `:<|>`.

After work, I'll try to flesh this idea out a bit more.

**Comment by shmish111** [comment]
OK, I would certainly love to see an example of this, sounds like a pretty good compromise.

**Comment by GambolingPangolin** [comment]
@shmish111 check out the PR I just opened, [this branch][1] with examples, and in particular [this server definition][2].

[1]: https://github.com/GambolingPangolin/servant-jsonrpc/tree/examples
[2]: https://github.com/GambolingPangolin/servant-jsonrpc/blob/examples/servant-jsonrpc-examples/server/Main.hs

**Comment by shmish111** [comment]
I think that looks really nice now.

**Comment by GambolingPangolin** [comment]
Great!  I'll go ahead and merge this and do a release to Hackage.
