### ISSUE TITLE
servant-jsonrpc-1.1.0: Relax upper bound on aeson, servant

### ISSUE THREAD

**Issue by mpilgrem** [bitnomial/servant-jsonrpc#12]
`servant-jsonrpc-1.1.0` specifies `aeson < 1.6` and `servant < 0.19` and `servant-jsonrpc-client-1.1.0` specifies `servant < 0.20` and `servant-client-core < 0.20` but, with `allow-newer`, they seem to compile fine with `aeson-2.1.2.1` and `servant-0.20.2` etc.

Please could the upper bounds be relaxed with a package revision on Hackage?

I specify `servant-jsonrpc-1.1.0`, rather than `1.1.1`, because of:
* #8

**Comment by GambolingPangolin** [comment]
Closed by #13
